### ISSUE TITLE
DWC 3.4.0

### ISSUE THREAD

**Issue by alexlinno** [Sindarius/ObjectCancelPlugin#1]
Hei Do you plan an update for DWC3.4.0....It doesn't run anymore since it requires DWC3.3.0
Thanks for the effort!

**Comment by Sindarius** [comment]
I'll look into getting this updated today. Thanks for the heads up!

**Comment by Sindarius** [comment]
New version available for 3.4.1

https://github.com/Sindarius/ObjectCancelPlugin/releases/tag/1.1.0
