### ISSUE TITLE
Cancel Popup 

### ISSUE THREAD

**Issue by MrExo3D** [Sindarius/ObjectCancelPlugin#2]
When you select an object. it asks.. Cancel Object, and then the options are Ok or Cancel

I would like to request to change the options to Yes or No,. for clarity.

![image](https://user-images.githubusercontent.com/10480179/180691846-92d1c61e-dddf-46be-a064-512081576841.png)

**Comment by Sindarius** [comment]
Changed in https://github.com/Sindarius/ObjectCancelPlugin/releases/tag/1.2.0
